# Generated by Django 4.2.13 on 2024-06-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(choices=[('3D Drawing', 'Drawing3D'), ('2D Drawing', 'Drawing2D'), ('Media Production', 'Media Production'), ('Animation', 'Animation'), ('Story Boards', 'Story Boards')], max_length=40)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
