# Generated by Django 4.2.13 on 2024-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('360 Campaigns', 'Drawing3D'), ('3D Animation', 'Drawing2D'), ('2D Animation', 'Media Production'), ('Media Production', 'Animation'), ('Digital Marketing', 'Story Boards')], max_length=40),
        ),
    ]
