# Generated by Django 4.2.13 on 2024-08-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('360 Campaigns', 'Campaigns360'), ('3D Animation', 'Animation3D'), ('2D Animation', 'Animation2D'), ('Media Production', 'Media Production'), ('Digital Marketing', 'Digital Marketing')], max_length=40),
        ),
    ]
