# Generated by Django 4.2.13 on 2024-06-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('blog_image', models.ImageField(blank=True, default='blogs/default-blog.png', null=True, upload_to='blogs/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('profile_pic', models.ImageField(blank=True, default='team_photos/default-employee.webp', null=True, upload_to='team_photos/')),
                ('job_title', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('behance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('review', models.TextField(max_length=1000)),
                ('profile_pic', models.ImageField(blank=True, default='team_photos/default-employee.webp', null=True, upload_to='testi_photos/')),
                ('company', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, default='icons/default-icon.png', null=True, upload_to='icons/'),
        ),
    ]
